### ISSUE TITLE
1.9.4 error

### ISSUE THREAD

**Issue by JonathanVil** [BossShop/BossShop#28]
I am getting this error when clicking on an item in my shop.
Version: Spigot 1.9.4

`[14:19:54 ERROR]: Could not pass event InventoryClickEvent to BossShop v2.5.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1851) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'cr' in plugin CrateReloaded v1.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:580) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.black_ixx.bossshop.core.BSBuy.giveRewardCommand(BSBuy.java:381) ~[?:?]
        at org.black_ixx.bossshop.core.BSBuy.giveReward(BSBuy.java:325) ~[?:?]
        at org.black_ixx.bossshop.listeners.InventoryListener.purchase(InventoryListener.java:117) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        ... 15 more
Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at com.hazebyte.crate.cratereloaded.j.h.getOnlinePlayers(PlayerUtil.java:33) ~[?:?]
        at com.hazebyte.crate.cratereloaded.j.h.L(PlayerUtil.java:21) ~[?:?]
        at com.hazebyte.crate.cratereloaded.c.c.e.a(GiveKey.java:32) ~[?:?]
        at com.hazebyte.crate.cratereloaded.h.a.onCommand(CommandManager.java:132) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:580) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        at org.black_ixx.bossshop.core.BSBuy.giveRewardCommand(BSBuy.java:381) ~[?:?]
        at org.black_ixx.bossshop.core.BSBuy.giveReward(BSBuy.java:325) ~[?:?]
        at org.black_ixx.bossshop.listeners.InventoryListener.purchase(InventoryListener.java:117) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-798f32d-0cd0397]
        ... 15 more
`

**Comment by Blackixx** [comment]
That error is caused here:

`Caused by: java.lang.NoSuchMethodError: org.bukkit.Bukkit.getOnlinePlayers()[Lorg/bukkit/entity/Player; at com.hazebyte.crate.cratereloaded.j.h.getOnlinePlayers(PlayerUtil.java:33) ~[?:?] at com.hazebyte.crate.cratereloaded.j.h.L(PlayerUtil.java:21) ~[?:?] at com.hazebyte.crate.cratereloaded.c.c.e.a(GiveKey.java:32) ~[?:?] at com.hazebyte.crate.cratereloaded.h.a.onCommand(CommandManager.java:132) ~[?:?] at `


Seems like your crate plugin is not up to date.
